schemaVersion: 1
tool: spooner
version: "0.14.0"
stages:
  2:
    date: "2026-08-09"
    templateVersion: "0.14.0"
    warnOnly: true
    files:
      - ".commitlintrc.json"
      - ".markdownlint-cli2.yaml"
      - ".pre-commit-config.yaml"
